wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717071837
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.10.13
      5: 0.17.0
      6: 4.41.1
      8:
      - 1
      - 5
      13: linux-x86_64
