# GLOBAL STUFF
model_version: 3.6B
dtype: bfloat16

effnet_checkpoint_path: /mnt/cluster_storage/models/effnet_encoder.safetensors
previewer_checkpoint_path: /mnt/cluster_storage/models/previewer.safetensors
generator_checkpoint_path: /mnt/cluster_storage/cascade-checkpoints/TEST-stageC-3b-canvadata-1X-2X-compile/generator.safetensors