wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717148050
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 55
      - 71
      - 83
      2:
      - 1
      - 2
      - 3
      - 11
      - 12
      - 45
      - 49
      - 55
      - 71
      - 83
      3:
      - 2
      - 19
      - 23
      4: 3.10.13
      5: 0.17.0
      6: 4.41.1
      8:
      - 1
      - 5
      13: linux-x86_64
stable_diffusion_checkpoint:
  desc: null
  value: stabilityai/stable-diffusion-xl-base-1.0
refiner_checkpoint:
  desc: null
  value: stabilityai/stable-diffusion-xl-refiner-1.0
offload_to_cpu:
  desc: null
  value: false
compile_model:
  desc: null
  value: false
prompt_1:
  desc: null
  value: Beach house overlooking turquoise water at sunset
prompt_2:
  desc: null
  value: Beach house overlooking turquoise water at sunset
negative_prompt_1:
  desc: null
  value: ''
negative_prompt_2:
  desc: null
  value: ''
num_images_per_prompt:
  desc: null
  value: 4
seed:
  desc: null
  value: 42
use_ensemble_of_experts:
  desc: null
  value: true
num_inference_steps:
  desc: null
  value: 50
num_refinement_steps:
  desc: null
  value: 50
high_noise_fraction:
  desc: null
  value: 0.8
