# GLOBAL STUFF
experiment_id: TEST-stageC-3b-canvadata-1X-2X-compile
checkpoint_path: /mnt/cluster_storage/cascade-checkpoints/
output_path: /home/ray/image-generation/StableCascade/output/
model_version: 3.6B

# WandB
wandb_project: stable-cascade
wandb_entity: angermanc


# TRAINING PARAMS
lr: 1.0e-4
batch_size: 1536
image_size: 384
# multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
grad_accum_steps: 12
updates: 500000
backup_every: 10000000
save_every: 1000
warmup_updates: 10000
use_fsdp: false

# GDF
# adaptive_loss_weight: True

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: s3://ingredient-generation-model-trainer.canva.com/image-generation/test/chris/cascade-data/
effnet_checkpoint_path: /mnt/cluster_storage/models/effnet_encoder.safetensors
previewer_checkpoint_path: /mnt/cluster_storage/models/previewer.safetensors
