# GLOBAL STUFF
experiment_id: test_compile_b_lite_fsdp_compile3
checkpoint_path: /mnt/cluster_storage/cascade-checkpoints/
output_path: test_train_b/output
model_version: 700M

# WandB
wandb_project: stable-cascade
wandb_entity: angermanc

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 512
image_size: 512
# multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
shift: 4
grad_accum_steps: 16
updates: 7550
save_every: 1000
backup_every: 100000000
warmup_updates: 10000
use_fsdp: true

# GDF
adaptive_loss_weight: True

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: pipe:aws s3 cp s3://ingredient-generation-model-trainer.canva.com/image-generation/test/chris/cascade-data/dataset_2X_0.tar -
effnet_checkpoint_path: /mnt/cluster_storage/models/effnet_encoder.safetensors
stage_a_checkpoint_path: /mnt/cluster_storage/models/stage_a.safetensors
