# GLOBAL STUFF
experiment_id: stage_b_3b_finetuning
checkpoint_path: stage_b_3b_test/checkpoint
output_path: stage_b_3b_test/output
model_version: 3B

# WandB
wandb_project: stable-cascade
wandb_entity: angermanc

# TRAINING PARAMS
lr: 1.0e-4
batch_size: 512
image_size: 512
# multi_aspect_ratio: [1/1, 1/2, 1/3, 2/3, 3/4, 1/5, 2/5, 3/5, 4/5, 1/6, 5/6, 9/16]
shift: 4
grad_accum_steps: 8
updates: 195
backup_every: 10000000000
save_every: 250
warmup_updates: 10000
use_fsdp: false

# GDF
adaptive_loss_weight: True

# ema_start_iters: 5000
# ema_iters: 100
# ema_beta: 0.9

webdataset_path: s3://ingredient-generation-model-trainer.canva.com/image-generation/test/chris/cascade-data/ds_1.tar
effnet_checkpoint_path: models/effnet_encoder.safetensors
stage_a_checkpoint_path: models/stage_a.safetensors
